# https://grafana.com/docs/loki/latest/setup/install/helm/reference/

loki:
  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: s3
    s3:
      endpoint: <endpoint>
      region: <AWS region>
      secretAccessKey: <AWS secret access key>
      accessKeyId: <AWS access key ID>
      s3ForcePathStyle: false
      insecure: false
