name: "Docker Image Build"

on:
  push:
    branches:
      - "{{ cookiecutter.ci_cd.branch }}"
    paths:
      - "image/**"
      - ".github/workflows/image.yaml"

jobs:
  build:
    name: QHub Build Dockerfile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - jupyterlab
          - jupyterhub
          - dask-worker
          - dask-gateway
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@master
{% if cookiecutter.provider == "aws" %}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: {{ '${{ secrets.AWS_ACCESS_KEY_ID }}' }}
          aws-secret-access-key: {{ '${{ secrets.AWS_SECRET_ACCESS_KEY }}' }}
          aws-region: {{ cookiecutter.amazon_web_services.region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Docker Build, Tag, and Push Image
        env:
          IMAGE_TAG: {{ '${{ github.sha }}' }}
          IMAGE_NAME: {{ '${{ steps.login-ecr.outputs.registry }}' }}/{{ cookiecutter.project_name }}-{{ '${{ matrix.dockerfile }}' }}
        run: |
          docker build -f image/Dockerfile.{{ '${{ matrix.dockerfile }}' }} -t $IMAGE_NAME:$IMAGE_TAG image
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Logout of Amazon ECR
        if: always()
        run: docker logout {{ '${{ steps.login-ecr.outputs.registry }}' }}
{% elif cookiecutter.provider == "gcp" %}
      - name: Configure GCP Credentials
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
      - name: 'Add GCP Credentials'
        run: |
          echo "$GOOGLE_CREDENTIALS" > /tmp/service-account.json
          gcloud auth activate-service-account --key-file=/tmp/service-account.json
        env:
          GOOGLE_CREDENTIALS: {{ '${{ secrets.GOOGLE_CREDENTIALS }}' }}
      - name: Add GCP Docker Credentials
        run: |
          gcloud auth configure-docker
      - name: Docker Build, Tag, and Push Image
        env:
          IMAGE_TAG: {{ '${{ github.sha }}' }}
          PROJECT_ID: {{ '${{ secrets.PROJECT_ID }}' }}
        run: |
          export IMAGE_NAME="gcr.io/$PROJECT_ID/{{ cookiecutter.project_name }}/qhub-{{ '${{ matrix.dockerfile }}' }}"
          docker build -f image/Dockerfile.{{ '${{ matrix.dockerfile }}' }} -t $IMAGE_NAME:$IMAGE_TAG image
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Docker Logout
        run: |
          docker logout
{% elif cookiecutter.provider == "azure" %}
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: {{ cookiecutter.project_name }}.azurecr.io
          username: {{ '${{ secrets.ARM_CLIENT_ID }}' }}
          password: {{ '${{ secrets.ARM_CLIENT_SECRET }}' }}
      - name: Docker Build, Tag, and Push Image
        env:
            IMAGE_TAG: {{ '${{ github.sha }}' }}
            IMAGE_NAME: azureqhubdev.azurecr.io/qhub-{{ '${{ matrix.dockerfile }}' }}
        run: |
          docker build -f image/Dockerfile.{{ '${{ matrix.dockerfile }}' }} -t $IMAGE_NAME:$IMAGE_TAG image
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Docker Logout
        run: |
          docker logout
{% elif cookiecutter.provider == "do" %}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: {{ '${{ secrets.DIGITALOCEAN_TOKEN }}' }}
      - name: Digital Ocean Docker Registry Login
        run: |
          doctl registry login
      - name: Docker Build, Tag, and Push Image
        env:
          IMAGE_TAG: {{ '${{ github.sha }}' }}
          IMAGE_NAME: registry.digitalocean.com/{{ cookiecutter.project_name }}/qhub-{{ '${{ matrix.dockerfile }}' }}
        run: |
          docker build -f image/Dockerfile.{{ '${{ matrix.dockerfile }}' }} -t $IMAGE_NAME:$IMAGE_TAG image
          docker push $IMAGE_NAME:$IMAGE_TAG
      - name: Docker Logout
        run: |
          docker logout
{% endif %}
