name: "Jupyterhub Infrastructure PR - deprecated"

on:
  public:

jobs:
  nothing-much:
    name: 'Fail because this file should be removed'
    runs-on: ubuntu-latest
    steps:
      - name: 'Fail'
        run: exit 1

