name: "QHub validate linter"

on:
  pull_request:
    branches:
      - master
    paths:
      - "qhub-config.yaml"


jobs:
  qhub-validate:
    name: 'Qhub'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Infastructure'
        uses: actions/checkout@master
        with:
          token: {{ '${{ secrets.REPOSITORY_ACCESS_TOKEN }}' }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install qhub
        run: |
          pip install qhub==0.2.3
      - name: 'Qhub Linterfy'
        env:
          PR_NUMBER: {{ '${{ github.event.number }}' }}
          REPO_NAME : {{ '${{ github.repository }}' }}
          GITHUB_TOKEN: {{ '${{ secrets.REPOSITORY_ACCESS_TOKEN }}' }}
        run: |
          qhub validate qhub-config.yaml --enable-commenting
