repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: 'qhub/template/(\.github/.*|infrastructure/jupyterhub.yaml|stages/07-kubernetes-services/modules/kubernetes/services/(clearml/chart/templates/.*|prefect/chart/templates/.*))'
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: '/qhub/template/'
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        exclude: 'qhub/template'
        args: [
          "--builtins=c"
        ]
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.3.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.3.0 hadolint
        args: [
            "--ignore", "DL3048",
            "--ignore", "DL3008",
            "--ignore", "DL3013",
            "--ignore", "DL3003",
        ]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.13
    hooks:
    - id: mdformat
      name: mdformat
      description: "CommonMark compliant Markdown formatter"
      entry: mdformat
      language: python
      # This is to support a use case where pre-commit runs in Python 2.
      # Should eventually be removed, at latest when `minimum_pre_commit_version`
      # is set to 2.0.0.
      language_version: python3
      types: [markdown]
      minimum_pre_commit_version: '1.0.0'
