name: qhub-dev
channels:
  - conda-forge
dependencies:
  - cookiecutter ==1.7.2
  - gitignore-parser==0.0.8
  - ruamel.yaml
  - cloudflare
  - auth0-python
  - pydantic
  - pynacl
  - bcrypt
  - python-kubernetes

  # dev dependencies
  - flake8 ==3.8.4
  - black ==20.8b1
  - twine
  - pytest
  - diagrams
  - jhub-client
