name: "Docker Image Build - Pull Request"

on:
  pull_request:
    branches:
      - master
    paths:
      - "image/**"
      - ".github/workflows/image-pr.yaml"

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - jupyterlab
          - jupyterhub
          - dask-gateway
          - dask-worker
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@master
      - name: Build Image
        env:
          IMAGE_TAG: {{ '${{ github.sha }}' }}
        run: |
          docker build -f "image/Dockerfile.{{ '${{ strategy.dockerfile }}' }}" -t "qhub-{{ '${{ strategy.dockerfile }}' }}:$IMAGE_TAG" image
