name: default
channels:
  - conda-forge
dependencies:
 # general
 - pip

 # jupyterhub/jupyterlab
 - nb_conda_kernels
 - ipython > 7
 - jupyter-server-proxy
 - "jupyter_server>=1.15.6 | <1.15"
 - jupyterlab >=3
 - jupyter_client
 - jupyter_console
 - jupyterhub==1.5.0
 - nbconvert
 - nbval
 - retrolab

 # jupyterlab extensions
#  - dask_labextension >=5.0.0
 - jupyterlab-git >=0.30.0
 - sidecar >=0.5.0
 - jupyter-videochat >=0.5.0
 - ipywidgets >=7.6
 - ipyleaflet >=0.13.5
 - pyviz_comms >=2.0.1
 - jupyter-resource-usage >=0.6.0
 - nbgitpuller

 # cds dashboards
 - cdsdashboards-singleuser >=0.6.1
 - jhsingle-native-proxy >=0.7.6

 # viz tools
 - param
 - python-graphviz
 - plotly >=5.0

 # testing, docs, linting
 - pytest
 - hypothesis
 - flake8
 - sphinx
 - pytest-cov
 - black
 - isort
 - importnb

 # vscode
 - code-server >= 3.2

 - pip:
     # vscode jupyterlab launcher
     - git+https://github.com/betatim/vscode-binder
     - git+https://github.com/dask/dask-labextension.git@main
