apiVersion: v1
kind: Secret
metadata:
  name: prefect-token
data:
  prefectToken: "{{ .Values.prefectToken | b64enc }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-token
data:
  jupyterHubToken: "{{ .Values.jupyterHubToken | b64enc }}"

---
{{ $index := dict "index" "0" }}
{{- range $k, $v := .Values.secretEnvVars }}
{{ $i := get $index "index" }}
{{ $ni := add1 $i }}
apiVersion: v1
kind: Secret
metadata:
  name: prefect-envsecret-{{ $i }}
data:
  prefectEnvSecret{{ $i }}: "{{ $v | b64enc }}"
{{ $_ := set $index "index" $ni }}
---
{{ end }}