name: default
channels:
  - conda-forge
dependencies:
 # general
 - pip

 # jupyterhub/jupyterlab
 - nb_conda_kernels
 - ipython > 7
 - jupyter-server-proxy
 - jupyterlab >=3
 - jupyter_client
 - jupyter_console
 - jupyterhub
 - nbconvert
 - nbval

 # jupyterlab extensions
 - dask_labextension >=5.0.0
 - jupyterlab-git >=0.30.0
 - sidecar >=0.5.0
 - jupyter-videochat >=0.5.0
 - ipywidgets >=7.6
 - ipyleaflet >=0.13.5
 - pyviz_comms >=2.0.1
 - jupyter-resource-usage >=0.6.0
 - nbgitpuller

 # cds dashboards
 - cdsdashboards-singleuser >=0.5.7
 - jhsingle-native-proxy >=0.7.6

 # viz tools
 - param
 - python-graphviz
 - plotly >=5.0

 # testing, docs, linting
 - pytest
 - hypothesis
 - flake8
 - sphinx
 - pytest-cov
 - black
 - isort
 - importnb

 - pip:
   # See install-conda-environment.sh when editing this section.
    - https://github.com/dirkcgrunwald/jupyter_codeserver_proxy-/archive/5596bc9c2fbd566180545fa242c659663755a427.tar.gz

