name: base
channels:
  - conda-forge
dependencies:
 # general
 - pip

 # jupyterhub/jupyterlab
 - nb_conda_kernels
 - ipython > 7
 - jupyter-server-proxy
 - jupyterlab-git
 - ipywidgets
 - jupyterlab ==2
 - jupyter_client
 - jupyter_console
 - jupyterhub
 - nodejs >= 10
 - nbconvert
 - nbval
 - dask_labextension

 # viz tools
 - panel
 - param
 - python-graphviz
 - ipyleaflet

 # testing, docs, linting
 - pytest
 - hypothesis
 - flake8
 - sphinx
 - pytest-cov
 - black
 - isort
 - importnb

 - pip:
   - jupyter-videochat
