name: base
channels:
  - conda-forge
dependencies:
 # general
 - pip

 # jupyterhub/jupyterlab
 - nb_conda_kernels
 - ipython > 7
 - jupyter-server-proxy
 - jupyterlab >=3
 - jupyter_client
 - jupyter_console
 - jupyterhub
 - nbconvert
 - nbval

 # jupyterlab extensions
 - dask_labextension >=5.0.0
 # jupyterlab-git >= #
 - jupyter-videochat
 - ipywidgets >=7.6
 - ipyleaflet >=0.13.5
 - pyviz_comms >=2.0.1

 # viz tools
 - panel
 - param
 - python-graphviz

 # testing, docs, linting
 - pytest
 - hypothesis
 - flake8
 - sphinx
 - pytest-cov
 - black
 - isort
 - importnb

 - pip: []
