# general
pip

# jupyterhub/jupyterlab
nb_conda_kernels
ipython > 7
jupyter-server-proxy
jupyterlab-git
ipywidgets
jupyterlab < 2.0
jupyter_client < 6.0
jupyter_console
jupyterhub
nodejs
nbconvert
nbval
dask_labextension

# dask
dask==2.14.0
distributed
dask-gateway=0.6.1

# numerical
numba
numpy
pandas

# s3 utits
s3fs
boto3

# viz tools
panel
param
python-graphviz

# testing, docs, linting
pytest
hypothesis
flake8
sphinx
pytest-cov
black
isort
