name: base
channels:
  - conda-forge
dependencies:
 - pip==21.1.2
 - jupyterhub==1.4.1
 - jupyterhub-kubespawner==1.0.0
 - bcrypt==3.2.0
 - oauthenticator==14.0.0
 - escapism==1.0.1
 - cdsdashboards==0.5.7
 - pip:
   - qhub-jupyterhub-theme==0.3.1
