name: base
channels:
  - conda-forge
dependencies:
 - pip
 - jupyterhub>=1.3.0
 - bcrypt
 - oauthenticator
 - escapism
 - cdsdashboards>=0.5.0
 - pip:
   - jupyterhub-kubespawner>=0.16.1
   - qhub-jupyterhub-theme==0.3.1
