name: base
channels:
  - conda-forge
dependencies:
 - pip
 - jupyterhub >= 1.3.0
 - bcrypt
 - oauthenticator
 - escapism
 - cdsdashboards
 - pip:
   - jupyterhub-kubespawner >= 0.16.1
   - qhub-jupyterhub-theme==0.3.1
   - cdsdashboards==0.5.0-b2
