repos:
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://github.com/prettier/prettier
    rev: d746cd7
    hooks:
      - id: prettier
        args: [--prose-wrap=preserve]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: b08e15c
    hooks:
      - id: isort
