name: "Build Docker Images"

on:
  create: # Branch (so that the Docker image tags exist for a new branch when pushed)
          # even if nothing on 'paths' below is changed.
    branches:
      - '**'

  push:
    paths:
      - "qhub/template/{{ cookiecutter.repo_directory }}/image/**"
      - ".github/workflows/image.yaml"

    branches: # Only on paths above
      - '**'

    tags: # Always, regardless of paths above
      - '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  jupyterlab:
    name: 'Build Docker Images'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - jupyterlab
          - jupyterlab-centos
          - jupyterhub
          - dask-worker
          - dask-worker-centos
          - dask-gateway
    steps:
      - name: 'Checkout Infrastructure'
        uses: actions/checkout@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay Container Registry
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: |
            "quansight/qhub-${{ matrix.dockerfile }}"
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build docker
        uses: docker/build-push-action@v2
        with:
          context: ./qhub/template/"{{ cookiecutter.repo_directory }}"/image
          file: "./qhub/template/{{ cookiecutter.repo_directory }}/image/Dockerfile.${{ matrix.dockerfile }}"
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ steps.meta.outputs.tags }}
            quay.io/${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Lint Dockerfiles
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: ./qhub/template/\{\{\ cookiecutter.repo_directory\ \}\}/image/Dockerfile.${{ matrix.dockerfile }}
          output_format: tty
          error_level: 0
