name: "Docker Image Build - Pull Request"

on:
  pull_request:
    branches:
      - main
    paths:
      - "qhub/template/{{ cookiecutter.repo_directory }}/image/**"
      - ".github/workflows/image-pr.yaml"

jobs:
  build:
    name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - jupyterlab
          - jupyterhub
          - dask-worker
          - dask-gateway
    steps:
      - name: 'Checkout Image'
        uses: actions/checkout@main
      - name: Build Image
        working-directory: "qhub/template/{{ cookiecutter.repo_directory }}/image"
        env:
          IMAGE_NAME: 'quansight/qhub-${{ matrix.dockerfile }}'
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f "Dockerfile.${{ matrix.dockerfile }}" -t $IMAGE_NAME:$IMAGE_TAG .
