name: Update API docs

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_api:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ./docs/api_docs
    steps:
      - name: Check out repository ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install nebari and docs dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e "../..[docs]"

      - name: Look for changes to cli files
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: |
            nebari/cli/*

      - name: Look for file changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"

      - name: Generate new API docs
        run: |
          echo "generate the new docs"
          pydoc-markdown -I "../../" -p nebari --render-toc > api_temp.md
          echo "make modifications to clean up"
          python api_doc_mods.py --autogen_path api_temp.md --outpath api_doc.md

      - name: Lint the new docs
        run: |
          set -e
          echo "run linting and formatting"
          pre-commit run --files api_doc.md
          echo "run it again to prove its clean now"
          pre-commit run --files api_doc.md

      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "::set-env name=changes_exist::true"
          else
            echo "::set-env name=changes_exist::false"
          fi

      - name: Create Pull Request in code repo
        id: cpr
        uses: peter-evans/create-pull-request@v4
        if: ${{ env.changes_exist == 'true' }}
        with:
          token: ${{ secrets.NEBARI_SENSEI_API_DOCS_PR_OPENER }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: auto_api_doc_update
          delete-branch: true
          title: '[AUTO] Update API doc'
          body: |
            Update API doc
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            "area: documentation ðŸ“–"
          draft: false
